// flow-typed signature: 350ad3418e1e2e6d7b16e1d3d70cd250
// flow-typed version: <<STUB>>/lodash.template_v4.4.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.template' {
  declare type TemplateSettings = {
    escape?: RegExp,
    evaluate?: RegExp,
    imports?: Object,
    interpolate?: RegExp,
    variable?: string,
  };

  declare module.exports: (template?: string, options?: TemplateSettings) => (opts?: Object) => string
}
